### ISSUE TITLE
Add graphical projects

### ISSUE THREAD

**Issue by lbarbaglia** [devSwoop/epidocker#1]
When I start a graphical project, I'm getting this error: 

`Failed to open X11 display; make sure the DISPLAY environment variable is set correctly`

Maybe you can add support of graphical projects ?

**Comment by viincenb** [comment]
I will do it :smiley:

**Comment by lbarbaglia** [comment]
Thank you very much :)

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f603.png)

**Comment by viincenb** [comment]
I just published a new version, it may fix your issue (or not...).<br>
Update your epidocker (the new version should be 1.4.0), then type `epidocker run --graphic` in your project directory, and try to run your project in the created container.<br>
Hope it will work for you :pray:

**Comment by lbarbaglia** [comment]
Thank you for your reactivity!! :+1: 
I got this just after I lauch `epidocker run --graphic` :
`/bin/sh: 1: locate: not found`
and
`/usr/lib/node_modules/epidocker/lib/utils.js:11
Epidocker was looking for Intel driver library (i965_dri.so) but did not find it...`

I work on Deepin Linux that's why I need Docker for my projects

**Comment by viincenb** [comment]
You need to have the `locate` command installed, I use it to locate libraries. You should try to `sudo apt-get install mlocate`. Retry to run your project when you got the command installed 🙂

**Comment by lbarbaglia** [comment]
I had a `locate: can not stat () '/var/lib/mlocate/mlocate.db': No such file or directory`
I check on Internet and I just had to do `sudo updatedb` to solve it
But now :
![deepinscreenshot_select-area_20180208232400](https://user-images.githubusercontent.com/35603025/36001618-2ce0f1d8-0d27-11e8-8fa7-3fa9398567d8.png)

**Comment by viincenb** [comment]
I did not expect this kind of error... I will try to reproduce and fix it asap 😉

**Comment by lbarbaglia** [comment]
Thanks ;)

**Comment by viincenb** [comment]
I reproduced your error and fixed it, update your epidocker and tell me what you got now :blush:

**Comment by lbarbaglia** [comment]
Now I can lauch 'epidocker run --graphic' but now when I tried to launch my project I got :
```
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  49
  Current serial number in output stream:  50
```

**Comment by viincenb** [comment]
Add   `LIBGL_DEBUG=verbose` before your command line
```bash
LIBGL_DEBUG=verbose ./binary arg1 [...]
```
and show me the output

**Comment by lbarbaglia** [comment]
Here's the output :
```
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /root/.drirc: No such file or directory.
libGL: pci id for fd 4: 8086:5916, driver i965
libGL: OpenDriver: trying /usr/lib64/dri/tls/i965_dri.so
libGL: OpenDriver: trying /usr/lib64/dri/i965_dri.so
libGL: dlopen /usr/lib64/dri/i965_dri.so failed (/usr/lib64/dri/i965_dri.so: wrong ELF class: ELFCLASS32)
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL: pci id for fd 4: 8086:5916, driver i965
libGL: OpenDriver: trying /usr/lib64/dri/tls/i965_dri.so
libGL: OpenDriver: trying /usr/lib64/dri/i965_dri.so
libGL: dlopen /usr/lib64/dri/i965_dri.so failed (/usr/lib64/dri/i965_dri.so: wrong ELF class: ELFCLASS32)
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL: OpenDriver: trying /usr/lib64/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib64/dri/swrast_dri.so
libGL: dlopen /usr/lib64/dri/swrast_dri.so failed (/usr/lib64/dri/swrast_dri.so: wrong ELF class: ELFCLASS32)
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  49
  Current serial number in output stream:  50
```

**Comment by viincenb** [comment]
**I'm still here**
I've done some research and I think this issue can be fixed by modifying the Docker image (install some packages). If I'm right, running `dnf install mesa-*` in your container should allow you to run your project. If it does not fix the issue, show me the error.

_Update your epidocker, I removed something which should be useless with this new method_

**Comment by viincenb** [comment]
I think the last update will to the trick, I close this issue... For now.

**Comment by lbarbaglia** [comment]
Here's the new error that I had:
![deepinscreenshot_select-area_20180306121655](https://user-images.githubusercontent.com/35603025/37029585-4ed77d14-2138-11e8-99ce-a09fcdb27c42.png)

The update delete some of the errors but not all.

**Comment by viincenb** [comment]
Did you run `epidocker update` twice as mentioned in the Readme  (or run `dnf install mesa-*` in your container) ? Your Docker image has to be updated.
I am able to run several graphic project, if you still can't run your project I will need your binary to reproduce your bug.

_Also, be sure to compile your project in the container_

**Comment by lbarbaglia** [comment]
Sorry, I didn't saw it now it work perfectly thanks :smile:
