### ISSUE TITLE
Debug configuration

### ISSUE THREAD

**Issue by pmondon** [devSwoop/epidocker#3]
Hi,

We cannot run GDB on epidocker. It must be on the launch configuration of docker.

Thank you for your time.
Sincerly

**Comment by viincenb** [comment]
It works for me.. Can you give me more informations such as screenshot of your error please ?

**Comment by pmondon** [comment]
![capture du 2018-03-05 14-13-06](https://user-images.githubusercontent.com/26172630/36976896-76329ff6-207f-11e8-8388-d131ccc793e1.png)
Here is the screen shot.

**Comment by viincenb** [comment]
Fixed by adding `dnf -y debuginfo-install glibc-2.25-13.fc26.x86_64` in the Docker image. The update will be available soon, you will need to `epidocker update` (do it twice if your version is below 1.4.3).
